msn_dj/accounts/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from .views import SignupView, profile, profile_update, AboutUpdateView, friend_add, AboutCreateView, friends_confirmation
from django.http import HttpResponse

app_name = 'accounts'

urlpatterns = [
     path('signup/', SignupView.as_view(), name='signup'),
     path('profile/<int:user_id>/', profile, name='profile'),
     path('about/', profile_update, name='about'),
     path('aboutupdate/<int:pk>/', AboutUpdateView.as_view(), name='aboutupdate'),
     path('aboutcreate/', AboutCreateView.as_view(), name='aboutcreate'),
     path('friend_add/<int:pk>/', friend_add, name='friend_add'),
     path('friends_confirmation/<int:pk>/', friends_confirmation, name='friends_confirmation'),
]

msn_dj/msn_app/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'msn_app'

urlpatterns = [
    path('', views.index, name='index'),
]

msn_dj/msn_dj/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('msn/', include('msn_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

msn_dj/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

User._meta.get_field('email').blank = False


class About(models.Model):
    date_birth = models.DateField(verbose_name='Дата рождения')
    city = models.ForeignKey('City', on_delete=models.SET_NULL, null=True, verbose_name='Город')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, verbose_name='Пользователь', unique=True)
    hobbies = models.TextField(max_length=500, verbose_name='Хобби')
    main_photo = models.ImageField(upload_to='users_photo', verbose_name='Фотография', null=True, blank=True)

class Profile(User):
    date_birth = models.DateField(verbose_name='Дата рождения')
    city = models.ForeignKey('City', on_delete=models.SET_NULL, null=True, verbose_name='Город')
    hobbies = models.TextField(max_length=500, verbose_name='Хобби')
    main_photo = models.ImageField(upload_to='users_photo', verbose_name='Фотография', null=True, blank=True)


class City(models.Model):
    name = models.TextField(max_length=150)
    
    def __str__(self):
        return self.name


class Friend(models.Model):
    user_who_add = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, verbose_name='Пользователь', related_name='User')
    user_with_add = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.RESTRICT, verbose_name='Друг', related_name='Friend')
    accept = models.BooleanField(verbose_name='Приглашение от пользователя', null=True)

msn_dj/accounts/forms.py
from pyexpat import model
from .models import About
from django.forms import HiddenInput, ModelForm, SelectDateWidget, DateInput
from datetime import datetime
from django.contrib.auth.forms import UserModel, UserCreationForm
from django.db import models

class AboutForm(ModelForm):
    
    class Meta:
        
        cur_year = datetime.today().year
        year_range = tuple([i for i in range(cur_year - 100, cur_year + 1)])

        model = About
        fields = ('date_birth', 'city', 'hobbies', 'main_photo')
        widgets = {
            'date_birth': SelectDateWidget(years=year_range),
            # 'user': HiddenInput(),
            # 'id': HiddenInput(),
            # 'date_birth': DateInput(attrs={'type':'date'})
            }


class RigisterUserForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ('username', 'email', 'password1', 'password2')


class FriendAddForm(ModelForm):
    class Meta:
        fields = ('user_who_add', 'user_with_add', 'accept')

msn_dj/accounts/views.py
from asyncio.windows_events import NULL
from dataclasses import field
from distutils.log import error
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User

from .models import About, Friend
from .forms import AboutForm, RigisterUserForm, FriendAddForm
from django.views.generic.edit import CreateView, UpdateView
from django.db import transaction
from django.http import HttpResponseRedirect


class SignupView(generic.CreateView):
    form_class = RigisterUserForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


class AboutUpdateView(UpdateView):
    template_name = 'about.html'
    form_class = AboutForm
    model = About
    
    def get_success_url(self):
        return reverse('accounts:profile')


class AboutCreateView(CreateView):
    template_name = 'about.html'
    form_class = AboutForm
    success_url = reverse_lazy('accounts:profile')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

def profile(request, user_id):
   
    template_name = 'profile.html'
    
    about = About.objects.get(user_id=user_id)

    invitation_friends = Friend.objects.filter(user_with_add=request.user.id)
    invitation_friends = invitation_friends.filter(accept=False)
    invitation_friends_id = []
    for invitation_friend in invitation_friends:
        invitation_friends_id.append(invitation_friend.user_who_add_id)

    invitation_friends_inc = Friend.objects.filter(user_who_add_id=request.user.id)
    invitation_friends_inc = invitation_friends_inc.filter(accept=False)
    invitation_friends_id_inc = []
    for invitation_friend_inc in invitation_friends_inc:
        invitation_friends_id_inc.append(invitation_friend_inc.user_with_add_id)

    friends = Friend.objects.filter(user_with_add=request.user.id)
    friends = friends.filter(accept=True)
    friends_id = []
    for friend in friends:
        friends_id.append(friend.user_who_add_id)

    friend_candidat_list = User.objects.exclude(pk=request.user.id)
    friend_candidat_list = friend_candidat_list.exclude(pk__in=invitation_friends_id)
    friend_candidat_list = friend_candidat_list.exclude(pk__in=friends_id)
    friend_candidat_list = friend_candidat_list.exclude(pk__in=invitation_friends_id_inc)
    
    context = {'friends' : friends,
               'invitation_friends' : invitation_friends,
               'invitation_friends_inc' : invitation_friends_inc,
               'friend_candidat_list' : friend_candidat_list,
               'about' : about
               }
               
    return render(request, template_name, context)

def profile_update(request):
    try:
        about_db = About.objects.get(user_id=request.user.id)
        return HttpResponseRedirect(reverse('accounts:aboutupdate', kwargs={'pk':about_db.id}))
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('accounts:aboutcreate'))
                     
def friend_add(request, pk):
    
    friend = User.objects.get(pk=pk)
    model_friend = Friend()
    model_friend.user_who_add = request.user
    model_friend.user_with_add = friend
    model_friend.accept = True

    model_friend2 = Friend()
    model_friend2.user_who_add = friend
    model_friend2.user_with_add = request.user
    model_friend2.accept = NULL

    try:
        with transaction.atomic():
            model_friend.save()
            model_friend2.save()

    except error as e:
        print(e)
    
    return redirect(reverse_lazy('accounts:profile'))

def friends_confirmation(request, pk):
    model_friend = Friend()
    model_friend.accept = True
    model_friend.pk = pk
    model_friend.save(update_fields=['accept'])

    return redirect(reverse_lazy('accounts:profile'))

def friends(request):
    pass

msn_dj/msn_app/views.py
from re import template
from django.shortcuts import render

def index(request):
    template = 'index.html'
    context = {}
    return render(request, template, context)

msn_dj/msn_dj/views.py
from django.shortcuts import render

def index(request):
    template = 'index.html'
    context = {}
    return render(request, template, context)

msn_dj/accounts/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>Обо мне</h1>
    <form action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Записать</button>
    </form>    
{% endblock %}

msn_dj/accounts/templates/profile.html
{% extends 'base.html' %}
{%load static%}

{% block content %}
    <h1>Кабинет пользователя</h1>
    <p>Добрый день, {{ user.username }}</p>
    <a href="{% url 'accounts:about' %}">Редактировать обо мне</a>
    <h2>Друзья</h2>
    <ul>
    {% for fc in friends %}
        <li><a href="{% url 'accounts:profile' fc.user_who_add.id %}">{{fc.user_who_add.username}}</a></li> 
    {%endfor%}
    </ul> 
    <h2>Заявки в друзья</h2>
    {%if invitation_friends_inc%}
    <h3>Входящие</h3>
    <ul>
        {% for fc in invitation_friends_inc %}
            <li>{{fc.user_who_add.username}} <a href="{% url 'accounts:friends_confirmation' fc.id %}">Принять</a></li> 
        {%endfor%}
    </ul>
    {%endif%}
    {%if invitation_friends%}     
    <h3>Исходящие</h3>
    <ul>
        {% for fc in invitation_friends %}
            <li>{{fc.user_who_add.username}}</li> 
        {%endfor%}
    </ul>
    {%endif%}       
    <h2>Предлагаем друзей</h2>
    <ul>
    {% for fc in friend_candidat_list %}
        <li>{{fc.username}} <a href="{% url 'accounts:friend_add' fc.id %}">Добавить</a></li> 
    {%endfor%}
    </ul>
{% endblock %}

{% block user_blog %}
    {% if about.main_photo %}
        <img src="{{about.main_photo.url}}" class="card-img-top" alt="...">
    {% else %}
        <img src="{% static 'img/blank.png' %}" class="card-img-top" alt="...">
    {% endif %}
    <p>Дата рождения: {{about.date_birth}}</p>
    <p>Город: {{about.city}}</p>
    <p>Хобби: {{about.hobbies}}</p>
{% endblock %}

msn_dj/accounts/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Зарегистрироваться</button>
    </form>
{% endblock %}

msn_dj/msn_dj/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Главная страница</h1>
{% endblock %}

msn_dj/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MSN</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>

    {% include 'menu.html' %}

    <div class="container text-center">
      <div class="row align-items-start">
        <div class="col-3">
          {% block content %}
            <h1>Hello, world!</h1>
          {% endblock %}
        </div>
        <div class="col-6">
          {% block user_blog %}
            One of three columns
          {% endblock %}
        </div>
        <div class="col-3">
          
        </div>
      </div>
    </div>    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

msn_dj/templates/menu.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Главная</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:profile' user.id %}">Моя страница</a>
        </li>
        <li class="nav-item" title="{{ user.username }}">
          <a class="nav-link" href="{% url 'logout' %}">Выход ({{ user.username }})</a>
        </li>          
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Регистрация</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login'  %}">Вход</a>
        </li>
        {% endif%}
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MSN</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>

    {% include 'menu.html' %}

    <div class="container text-center">
      <div class="row align-items-start">
        <div class="col-3">
          {% block content %}
            <h1>Hello, world!</h1>
          {% endblock %}
        </div>
        <div class="col-6">
          {% block user_blog %}
            One of three columns
          {% endblock %}
        </div>
        <div class="col-3">
          
        </div>
      </div>
    </div>    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Главная страница</h1>
{% endblock %}

templates/menu.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Главная</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:profile' user.id %}">Моя страница</a>
        </li>
        <li class="nav-item" title="{{ user.username }}">
          <a class="nav-link" href="{% url 'logout' %}">Выход ({{ user.username }})</a>
        </li>          
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Регистрация</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login'  %}">Вход</a>
        </li>
        {% endif%}
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>